// Generates src/SimplyPdf/Fonts/StandardFontMetrics.Data.g.cs from the Adobe Core 14 AFM files.
//
// Usage: dotnet run --project tools/AfmToCSharp -- <afm-directory> <output-file>
//
// The AFM files use AdobeStandardEncoding, but PDF text in SimplyPdf is written with
// WinAnsiEncoding, so widths are looked up by glyph *name* and re-indexed by WinAnsi code.

using System.Globalization;
using System.Text;

if (args.Length != 2)
{
    Console.Error.WriteLine("Usage: AfmToCSharp <afm-directory> <output-file>");
    return 1;
}

var afmDirectory = args[0];
var outputFile = args[1];

// Enum member name -> PostScript font name. Order defines the enum order in the library.
(string Member, string PostScriptName)[] fonts =
[
    ("Helvetica", "Helvetica"),
    ("HelveticaBold", "Helvetica-Bold"),
    ("HelveticaOblique", "Helvetica-Oblique"),
    ("HelveticaBoldOblique", "Helvetica-BoldOblique"),
    ("TimesRoman", "Times-Roman"),
    ("TimesBold", "Times-Bold"),
    ("TimesItalic", "Times-Italic"),
    ("TimesBoldItalic", "Times-BoldItalic"),
    ("Courier", "Courier"),
    ("CourierBold", "Courier-Bold"),
    ("CourierOblique", "Courier-Oblique"),
    ("CourierBoldOblique", "Courier-BoldOblique"),
];

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated>");
sb.AppendLine("//   Generated by tools/AfmToCSharp from the Adobe Core 14 AFM files. Do not edit by hand.");
sb.AppendLine("//   Font metrics: Copyright (c) 1985-1997 Adobe Systems Incorporated. All Rights Reserved.");
sb.AppendLine("//   Helvetica and Times are trademarks of Linotype-Hell AG and/or its subsidiaries.");
sb.AppendLine("// </auto-generated>");
sb.AppendLine();
sb.AppendLine("namespace SimplyPdf.Fonts;");
sb.AppendLine();
sb.AppendLine("internal static partial class StandardFontMetrics");
sb.AppendLine("{");

foreach (var (member, psName) in fonts)
{
    var afm = Afm.Parse(Path.Combine(afmDirectory, psName + ".afm"));
    var widths = new int[256];
    for (var code = 32; code < 256; code++)
    {
        var glyph = WinAnsi.GlyphNames[code - 32];
        if (!afm.WidthsByGlyph.TryGetValue(glyph, out var width))
        {
            throw new InvalidDataException($"{psName}: glyph '{glyph}' (WinAnsi {code}) missing from AFM.");
        }

        widths[code] = width;
    }

    var inv = CultureInfo.InvariantCulture;
    sb.AppendLine(inv, $"    private static readonly FontMetricsData {member}Data = new(");
    sb.AppendLine(inv, $"        \"{psName}\",");
    sb.AppendLine(inv, $"        ascender: {afm.Ascender}, descender: {afm.Descender}, capHeight: {afm.CapHeight}, xHeight: {afm.XHeight},");
    sb.AppendLine(inv, $"        bboxLeft: {afm.BBox[0]}, bboxBottom: {afm.BBox[1]}, bboxRight: {afm.BBox[2]}, bboxTop: {afm.BBox[3]},");
    sb.AppendLine("        widths:");
    sb.AppendLine("        [");
    for (var row = 0; row < 256; row += 16)
    {
        sb.Append("            ");
        sb.AppendJoin(", ", widths.Skip(row).Take(16).Select(w => w.ToString(CultureInfo.InvariantCulture)));
        sb.AppendLine(",");
    }

    sb.AppendLine("        ]);");
    sb.AppendLine();
}

sb.AppendLine("    private static readonly FontMetricsData[] AllData =");
sb.AppendLine("    [");
foreach (var (member, _) in fonts)
{
    sb.AppendLine(CultureInfo.InvariantCulture, $"        {member}Data,");
}

sb.AppendLine("    ];");
sb.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(outputFile))!);
File.WriteAllText(outputFile, sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
Console.WriteLine($"Wrote {outputFile} ({fonts.Length} fonts).");
return 0;

internal sealed class Afm
{
    public int Ascender { get; private set; }
    public int Descender { get; private set; }
    public int CapHeight { get; private set; }
    public int XHeight { get; private set; }
    public int[] BBox { get; private set; } = new int[4];
    public Dictionary<string, int> WidthsByGlyph { get; } = new(StringComparer.Ordinal);

    public static Afm Parse(string path)
    {
        var afm = new Afm();
        foreach (var line in File.ReadLines(path))
        {
            if (line.StartsWith("C ", StringComparison.Ordinal))
            {
                // C 32 ; WX 278 ; N space ; B 0 0 0 0 ;
                string? name = null;
                var width = 0;
                foreach (var part in line.Split(';', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries))
                {
                    var kv = part.Split(' ', 2, StringSplitOptions.TrimEntries);
                    switch (kv[0])
                    {
                        case "WX": width = int.Parse(kv[1], CultureInfo.InvariantCulture); break;
                        case "N": name = kv[1]; break;
                    }
                }

                if (name is not null)
                {
                    afm.WidthsByGlyph[name] = width;
                }

                continue;
            }

            var space = line.IndexOf(' ', StringComparison.Ordinal);
            if (space < 0)
            {
                continue;
            }

            var key = line[..space];
            var value = line[(space + 1)..].Trim();
            switch (key)
            {
                case "Ascender": afm.Ascender = int.Parse(value, CultureInfo.InvariantCulture); break;
                case "Descender": afm.Descender = int.Parse(value, CultureInfo.InvariantCulture); break;
                case "CapHeight": afm.CapHeight = int.Parse(value, CultureInfo.InvariantCulture); break;
                case "XHeight": afm.XHeight = int.Parse(value, CultureInfo.InvariantCulture); break;
                case "FontBBox":
                    afm.BBox = value.Split(' ', StringSplitOptions.RemoveEmptyEntries)
                        .Select(v => int.Parse(v, CultureInfo.InvariantCulture)).ToArray();
                    break;
            }
        }

        return afm;
    }
}

/// <summary>WinAnsiEncoding glyph names for codes 32..255 (PDF 32000-1:2008, Annex D.2).</summary>
internal static class WinAnsi
{
    // Codes 127, 129, 141, 143, 144 and 157 are undefined in WinAnsiEncoding; the spec says
    // viewers show them as "bullet", so their width is bullet's. 160 is a non-breaking space
    // and 173 a soft hyphen; both take the width of their visible counterparts.
    public static readonly string[] GlyphNames =
    [
        // 32..47
        "space", "exclam", "quotedbl", "numbersign", "dollar", "percent", "ampersand", "quotesingle",
        "parenleft", "parenright", "asterisk", "plus", "comma", "hyphen", "period", "slash",
        // 48..63
        "zero", "one", "two", "three", "four", "five", "six", "seven",
        "eight", "nine", "colon", "semicolon", "less", "equal", "greater", "question",
        // 64..79
        "at", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O",
        // 80..95
        "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "bracketleft", "backslash", "bracketright", "asciicircum", "underscore",
        // 96..111
        "grave", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o",
        // 112..127
        "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "braceleft", "bar", "braceright", "asciitilde", "bullet",
        // 128..143
        "Euro", "bullet", "quotesinglbase", "florin", "quotedblbase", "ellipsis", "dagger", "daggerdbl",
        "circumflex", "perthousand", "Scaron", "guilsinglleft", "OE", "bullet", "Zcaron", "bullet",
        // 144..159
        "bullet", "quoteleft", "quoteright", "quotedblleft", "quotedblright", "bullet", "endash", "emdash",
        "tilde", "trademark", "scaron", "guilsinglright", "oe", "bullet", "zcaron", "Ydieresis",
        // 160..175
        "space", "exclamdown", "cent", "sterling", "currency", "yen", "brokenbar", "section",
        "dieresis", "copyright", "ordfeminine", "guillemotleft", "logicalnot", "hyphen", "registered", "macron",
        // 176..191
        "degree", "plusminus", "twosuperior", "threesuperior", "acute", "mu", "paragraph", "periodcentered",
        "cedilla", "onesuperior", "ordmasculine", "guillemotright", "onequarter", "onehalf", "threequarters", "questiondown",
        // 192..207
        "Agrave", "Aacute", "Acircumflex", "Atilde", "Adieresis", "Aring", "AE", "Ccedilla",
        "Egrave", "Eacute", "Ecircumflex", "Edieresis", "Igrave", "Iacute", "Icircumflex", "Idieresis",
        // 208..223
        "Eth", "Ntilde", "Ograve", "Oacute", "Ocircumflex", "Otilde", "Odieresis", "multiply",
        "Oslash", "Ugrave", "Uacute", "Ucircumflex", "Udieresis", "Yacute", "Thorn", "germandbls",
        // 224..239
        "agrave", "aacute", "acircumflex", "atilde", "adieresis", "aring", "ae", "ccedilla",
        "egrave", "eacute", "ecircumflex", "edieresis", "igrave", "iacute", "icircumflex", "idieresis",
        // 240..255
        "eth", "ntilde", "ograve", "oacute", "ocircumflex", "otilde", "odieresis", "divide",
        "oslash", "ugrave", "uacute", "ucircumflex", "udieresis", "yacute", "thorn", "ydieresis",
    ];
}
